### ISSUE TITLE
Merge Models and OSes

### ISSUE THREAD

**Issue by justdave** [mozilla/inventory#54]
We have a lot of duplicates in both the Models and OSes tables, some are variant misspellings, others are exact dupes.  We could clean it up a lot if there were a way to merge them (delete all but one, move all references to the one that's kept)

**Comment by rtucker-mozilla** [comment]
It's not as easy to just merge them automatically. There was so much garbage data in SN from autodiscovery and user entries that many similar entries have been imported.

I can run a query to delete any entries that are unused. 


There are currently only 14 unused server models that can be deleted:

select id from server_models where id not in (select server_model_id from systems where server_model_id is not null);

There are currently 157 operating system that can be deleted

select id from operating_systems where id not in (select operating_system_id from systems where operating_system_id is not null);


There aren't many exact dupes as far as server_models go


MariaDB [inventory_mozilla_org]> select id, vendor,model, count(*) from server_models group by vendor,model having count(*) > 1;
+------+-------------+----------------+----------+
| id   | vendor      | model          | count(*) |
+------+-------------+----------------+----------+
|  157 |             |                |        2 |
| 1449 | Cisco       | WS-C3850-24S-E |        2 |
| 1436 | PAN PA-3020 | PAN PA-3020    |        8 |
+------+-------------+----------------+----------+


There are no dupe operating systems

MariaDB [inventory_mozilla_org]> select name,version, count(*) from operating_systems group by name,version having count(*) > 1;
Empty set (0.00 sec)
3 rows in set (0.00 sec)

I can run queries to update these exact dupes but ones that are  just barely off should be manually fixed as they are found.

**Comment by rtucker-mozilla** [comment]
delete from server_models where id not in (select server_model_id from systems where server_model_id is not null);
delete from operating_systems where id not in (select operating_system_id from systems where operating_system_id is not null);

**Comment by rtucker-mozilla** [comment]
This drastically reduced the amount of crap entries

**Comment by rtucker-mozilla** [comment]
@justdave if you want to go through now and tell me which entries to update I can run some SQL manually.

If you go to the server model list page and hover over the edit link you can get the id number of the proper and the incorrect entries. I can then easily run sql updates.

The following is a great example from inventory. (ID is the numeric part of the edit link):

Vendor | Model | ID
PAN | PA-220 | 1435
PAN PA | 220 |1439

You can tell me to update all 1439 to 1435 and then delete 1439.

Let me know if this makes sense.

**Comment by justdave** [comment]
> | 1449 | Cisco | WS-C3850-24S-E | 2 |
> | 1436 | PAN PA-3020 | PAN PA-3020 | 8 |

Hey, those are the two I actually noticed that prompted this issue being filed. :-)

> Vendor | Model | ID
> PAN | PA-220 | 1435
> PAN PA | 220 |1439
> 
> You can tell me to update all 1439 to 1435 and then delete 1439.

That works for me. :-)  Thanks!

**Comment by justdave** [comment]
There were a few of the variant misspelling variety IIRC but I'm out for a couple weeks, I'll investigate again when I'm back, and ask for those specifically when I find them again.
